version: "3"
services:
 storj:
  image : meldon/storj
  container_name: storj_1
  ports:
   - 4000:4000
  volumes: 
   - ./configs:/home/storj/configs
   - ./data:/home/storj/data
   - ./logs:/home/storj/logs